### ISSUE TITLE
[Issue]: Invoice payout issue for one of the seller

### ISSUE THREAD

**Issue by adityachaudhari** [paypal/mirakl-hyperwallet-connector#115]
Hi Team
we are recently live with the mirakl-hyperwallet connector, for our first payout we had 2 sellers to pay, for one of the seller, seller payment is successful however for other it failed.

We had a paypal funds issue ( less funds in the account ) which was the reason behind the 1st failure.
To solve this  we funded the account and tried again hitting **invoicesExtractJob**  this time expecting payment 'll be done to other sellers where payment failed in the first go, this time it failed with different error.

Below is the error ,
`
1677141228490,"{""log"":""23-02-2023 08:33:48.489 [HyperwalletMiraklScheduler_Worker-3] ERROR {\""id\"":\""15f518c6-82bd-46c9-966f-d4158a11d10a\"",\""subtype\"":\""InvoicesExtractBatchJob\"",\""itemType\"":\""Invoice\"",\""itemId\"":\""230187\"",\""type\"":\""BatchJob\""} com.paypal.invoices.invoicesextract.service.hyperwallet.impl.HyperWalletPaymentExtractServiceImpl - Something went wrong creating payment for invoice [230100].
1677141228490,"{""log"":""{
1677141228490,"{""log"":""  \""errorCode\"" : \""CONSTRAINT_VIOLATIONS\"",
1677141228490,"{""log"":""  \""errorMessage\"" : \""You must provide a value for this field\"",
1677141228490,"{""log"":""  \""exceptionMessage\"" : \""You must provide a value for this field\"",
1677141228490,"{""log"":""  \""responseStatusCode\"" : \""400\"",
1677141228490,"{""log"":""  \""responseMessage\"" : \""Bad Request\"",
1677141228490,"{""log"":""  \""responseBody\"" : \""-- encrypted --"",
1677141228490,"{""log"":""  \""errorDetailList\"" : [ {
1677141228490,"{""log"":""    \""code\"" : \""CONSTRAINT_VIOLATIONS\"",
1677141228490,"{""log"":""    \""fieldName\"" : \""**programToken**\"",
1677141228490,"{""log"":""    \""message\"" : \""You must provide a value for this field\""
1677141228490,"{""log"":""  }, {
1677141228490,"{""log"":""    \""code\"" : \""CONSTRAINT_VIOLATIONS\"",
1677141228490,"{""log"":""    \""message\"" : \""Please enter a valid **destinationToken**\""
1677141228490,"{""log"":""  } ]
1677141228490,"{""log"":""}
`

checked the token **Hyperwallet Bank Account Token** and **Hyperwallet User Token** for the failed seller those appeared to be fine .

Found l'll similar thread but not exactly same thread which is https://github.com/paypal/mirakl-hyperwallet-connector/issues/80 .
As suggested here tried restart of the mirakl-hyperwallet connector application but no-luck. 

Appreciate if you can help me figure our what else I need to check or re-verify or the way we can fix this.

many thanks.

### Environment

Live/Production

### Version :

4.17.0

### Expected Behavior

2nd seller payment must be pass through without errors as 1st passed after added back missing funds and after retrial of invoicesExtractJob.

### Actual Behavior

seller payment is failed with error  400 Bad request

""errorDetailList\"" : [ {
1677141228490,"{""log"":""    \""code\"" : \""CONSTRAINT_VIOLATIONS\"",
1677141228490,"{""log"":""    \""fieldName\"" : \""programToken\"",
1677141228490,"{""log"":""    \""message\"" : \""You must provide a value for this field\""
1677141228490,"{""log"":""  }, {
1677141228490,"{""log"":""    \""code\"" : \""CONSTRAINT_VIOLATIONS\"",
1677141228490,"{""log"":""    \""message\"" : \""Please enter a valid destinationToken\""

**Comment by adityachaudhari** [comment]
Hi Team,
Can you help with this request earliest possible ? **This is our production issue.** 
This is our first payout which got failed.
Sellers were expected the payment on 15th and because of this issue payment is not done yet.
Quick help is appreciated.

Please let me know if  any additional details are needed

**Comment by adityachaudhari** [comment]
Hi Team , 
Could you please help with the issue mentioned above, Its our prod env issue.
If you need any more details please let me know .

**Comment by javierpoloe2y** [comment]
Hi @adityachaudhari,

According to the logs, it looks like that the `destinationToken` (which is a bank account token) and the `programToken` have been sent empty when the payment was created in Hyperwallet.

This is really unexpected since there is an specific validation before sending the payment to ensure that those fields are not empty and also when the connector tried to pay the invoice for the first time it looks that the payment was created successfully (although it was rejected).

Can you attach the full logs of the invoice extraction job for the first run that failed because of the funds and also for the second manual run of the job?.

Also, the connector has an internal database that is used as a persistent cache. It's stored in the `/data` folder. Perhaps it has some invalid data (although this is rare to happen). You can try to delete the contents of that folder, restart the connector and re-run the job manually. If you are using docker you will need to remove the container and its associated volumes.

**Comment by adityachaudhari** [comment]
Hi @javierpoloe2y 
Thank you very much for the reply, appreciate that.

Below is the log .
[logs_hmc_15_16FEB.log](https://github.com/paypal/mirakl-hyperwallet-connector/files/10838789/logs_hmc_15_16FEB.log)

Please refer lines from 200 - to 261.
As requested this is the logs above when for the first time it worked for one seller and later failed due to insufficient funds.
And below attaching the logs where it failed again after adding the funds. ( please refer lines from 42 - 167)

[log-events-viewer-result (16).csv](https://github.com/paypal/mirakl-hyperwallet-connector/files/10838834/log-events-viewer-result.16.csv)

For the other suggestion to remove /data folder I am working with the OPS team and will update here the result of that.

Please let me know if you need additional details.

Thanks

**Comment by javierpoloe2y** [comment]
Hi @adityachaudhari,

I have reviewed the logs and I have some findings:

- The connector was trying to pay two invoices `230187` and `230188`.
- Payment of `230187` failed due to the error that you reported in the first message (`CONSTRAINT_VIOLATIONS`).
- Payment of `230188` partially failed:
    - An Hyperwallet payment for `230188` was successfully created.
    - A second Hyperwallet payment with id `230188-operatorFee` was created to pay the operator fees, and this one failed with the `INSUFFICIENT_FUNDS` error.

So when you fixed the funds problem, the payment that should have been created correctly in Hyperwallet was the operator fees for the invoice `230188`, but you didn't addressed the problems with the invoice `230187` that was failing for another reason.

After reviewing the code is really difficult that the invoice `230187` could have passed the validation phase with an empty bank account of program.

If removing the contents of `data` folder didn't work can you please review that:

- The shop that is the owner of invoice `230187` has the same program than the owner of `230188`.

Also I have some other questions regarding that shop:

- Did the bank account for the shop changed after it was exported for the first time to Hyperwallet. Did it's bank account token change? (You can see the history of changes for the fields of a shop in the Mirakl backend)

**Comment by adityachaudhari** [comment]
Hi @javierpoloe2y 
Thanks for response and additional questions .

Issue seems to be resolved after deleting the container and associated volume ( i.e. removal of old data and created fresh)
As I can see in logs payment is under process and created entries in hyperwallet.
Waiting for paid status reflect in Mirakl, seems it may take some time but i can see for one of the seller both payment entries are under process.

But, there is still one issue,
As you also observed correctly about payment of `230188  `in above comment ,
Payment for '230188 ' was done partially due to insufficient funds, where operator payment was not done.
**I was hoping this time when we resolve issue by deleting /data , this previously failed operator payment will also retrigger.
But seems it did not tried to re-trigger partially failed operator payment .**

Anything specific we need to trigger / any procedure is there for re-triggering partially failed operator payment ?

Thanks

**Comment by adityachaudhari** [comment]
Hi @javierpoloe2y 

Issue is partially resolved.
I confirm we got the "paid" status back in Mirakl for one of the seller. Thanks for suggestion to retry with recreating container.

But as mentioned in immediate above comment, for one of the seller we still have the issue where operator payment is not done in first go due to insufficient funds but in Mirakl we have received the "PAID" status.
We were expecting **"invoicesExtractJob"** will pick up partially failed operator payments for processing but it has not picked those.

**Is there any way we can trigger partially failed operator payment ?**

Out paypal representative suggested to ask connector team regarding the operator payment retry issue.
Please let me know if you need any additional information .

Thanks

**Comment by javierpoloe2y** [comment]
Hi @adityachaudhari ,

Since the invoice is already marked as `paid` in Mirakl, it will be ignored by the `invoiceExtractJob`. The connector has an automatic retry mechanism but in this case, the operator payment retries are already exhausted. We are trying to find a solution for this and will come back to you as soon as possible.

**Additional Info**: When a payment fails (the seller or the operator one) it's automatically retried up to 5 times according to this formula `timeOfLastFailure + 30 minutes * numberOfRetry`, which gives 450 minutes between the first failure and the last retry. That's why the retries for the operator payment are exhausted.

**Comment by adityachaudhari** [comment]
ok thanks @javierpoloe2y  for reply.
Thanks for the explanation about the retrial .

Our paypal representation also suggested if needed we can hit the API manually ,
https://docs.hyperwallet.com/content/api/v4/resources/payments/create

Would like to confirm from connector perspective , if its fine to hit Create Payment for failed operator payment .
Will this cause any issue for any next retries or any other connector code issue if one of the payment we have done manually in this special case?

Thanks

**Comment by javierpoloe2y** [comment]
Hi @adityachaudhari ,

Unfortunately, currently, the connector can't reprocess your failed operator fee payment and we don't have any workaround for that. So yes, the only solution is to create a payment manually in Hyperwallet.

Creating a manual payment shouldn't cause any issues in the connector, but to be completely sure of that, please ensure that the `clientPaymentId` of the payment in Hyperwallet is the same as the one generated by the connector. In this case, it should be `230188-operatorFee`.

You can reach the Hyperwallet support team if you need help creating the payment. I will close the ticket but don't hesitate to reopen it if you still have problems with this issue.
