### ISSUE TITLE
No buildInfo on 4.18.1 build 

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#116]
### Describe the Issue

The actuator /actuator/info does not return any info for images built using the bootBuildImage task.
I can see that the info is in application.properties,  and that running the task generates the meta-inf file, but the packed image doesn't seem to include it?

Please can you suggest? Thanks

### Environment

Live/Production

### Version

4.18.1

### Expected Behavior

info actuator returns version info

### Actual Behavior

blank :

build	{}

### Steps to Reproduce

run ./gradlew web:bootBuildImage

docker run <args>

access /actuator/info

expect to see: build info

**Comment by RussGarratt** [comment]
Seems like removing :

`	@ConditionalOnMissingBean
	@Bean
	public BuildProperties buildProperties() {
		return new BuildProperties(new Properties());
	}`

From: WebConnectorApplication

At least gives some info back:

build	
artifact	"web"
name	"web"
time	"2023-03-03T14:02:28.215Z"
version	"4.18.1"
group	"com.paypal"

Is it ok to remove that empty build properties?

**Comment by RussGarratt** [comment]
Thanks,
Might have to ask how you are running from the IDE in the future please?
Tried running it, just get issues regarding dependencies from the /web module.
End up creating docker image using bootBuildImage from web, then running it in docker
Thanks,
Russ

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

I personally use IntelliJ. I don't do anything special I simply import it as a Gradle project and it works. Usually, I change IntelliJ Gradle settings to not invoke Gradle to run the application or tests, because the IDE runner is faster:

![image](https://user-images.githubusercontent.com/97441435/224962407-2e83281f-72f3-41f2-8a21-90c80b5dbd40.png)

To run the application I simply go to the main SpringBoot class and run it from the IDE. You should remember that the connector needs some environment variables to run properly, so you need to edit the run configuration and add the environment variables.

In any case, importing it as a Gradle project, and having the correct environment variables should be enough to run it from IntelliJ.

**Comment by RussGarratt** [comment]
@javierpoloe2y 
Thanks for info, closing issue
