### ISSUE TITLE
[Question]: How do we migrate the connector to another environment please?

### ISSUE THREAD

**Issue by RussGarratt** [paypal/mirakl-hyperwallet-connector#133]
We currently have the connector running in one of our environments. (let's call it UAT1)
Given that we only have the one paypal test account, we would like to move the connector to another one of our environments.
Please can you suggest what we should do? (We have the H2 database file on EFS)

Connector -> has users / bank accounts / webhooks histories / infrastrusture dbs etc from Mirakl Env A

If we wanted to move the connector to another env:

* Mirakl (since it uses the same seeds) will have clashes in user/shop accounts - assume users.db keys by mirakl ID?
* Connector will have historical data
* Paypal will have all data from Mirakl A

We would like:

* Connector running against a new mirakl env (Mirakl B)

Should we:

* Request a new / clear existing UAT Hyperwallet data?
* Simply remove the DB files and start again after moving the connector to use Mirakl B?
* Something else?

Thanks and regards,
Russ

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

The information that is stored in the connector database is not critical. Basically, it only contains information about executed jobs, info about failed items that are scheduled to be retried, and some caches to speed up things. That means that at any moment you can delete it and the connector will continue working without problems. The only downside is that the next execution of the jobs is going to process more items, since jobs process all modified items since their last execution.

So if you have one UAT1 env and want to have a second UAT2 env, my recommendation is:

- Do a fresh installation of the connector on UAT2.
- Point the connector in UAT2 to a new Mirakl instance and to another Hyperwallet account.

**Comment by RussGarratt** [comment]
Thanks for the infoIf we were to use the same Hyperwallet account? Assume that would be a pain due to all the existing data? ThanksRussSent from my iPhoneOn 15 Sep 2023, at 08:32, Javier Polo ***@***.***> wrote:﻿
Hi @RussGarratt,
The information that is stored in the connector database is not critical. Basically, it only contains information about executed jobs, info about failed items that are scheduled to be retried, and some caches to speed up things. That means that at any moment you can delete it and the connector will continue working without problems. The only downside is that the next execution of the jobs is going to process more items, since jobs process all modified items since their last execution.
So if you have one UAT1 env and want to have a second UAT2 env, my recommendation is:

Do a fresh installation of the connector on UAT2.
Point the connector in UAT2 to a new Mirakl instance and to another Hyperwallet account.

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

If you were to use the same Hyperwallet account you would have problems with the IDs coming from Mirakl. Since you are using a new Mirakl instance, the ID counter for the different Mirakl entities will be at its starting point, so, for example, when you are importing a new shop from Mirakl, its ID will already exist in Hyperwallet belonging to a different shop.

**Comment by javierpoloe2y** [comment]
Hi @RussGarratt,

I hope we have answered your questions and helped you. We are going to close this issue, but feel free to reopen it if you need more support on this.
