### ISSUE TITLE
Not allowed to push to your repo but here would be the changes:

### ISSUE THREAD

**Issue by sairumea** [paypal/mirakl-hyperwallet-connector#146]
Not allowed to push to your repo but here would be the changes:

![changes](https://github.com/paypal/mirakl-hyperwallet-connector/assets/104622039/439bf822-cce6-470f-8ba8-7d2f1ac566c0)

_Originally posted by @RussGarratt in https://github.com/paypal/mirakl-hyperwallet-connector/issues/126#issuecomment-1957349328_

**Comment by RussGarratt** [comment]
Am I able to be added as a contributor to this project please?
Thanks,
Russ

**Comment by max6001** [comment]
Hi RussGarratt.

Instead of being added as a contributor directly to the project, which is typically reserved for maintainers or owners, you can contribute by forking the repository and then submitting a pull request.
Here are the steps to do so:
Go to the project’s GitHub page and click on the “Fork” button located in the upper right corner of the page. This will create a copy of the repository under your own GitHub account.
Clone the forked repository to your local machine using git clone command.
Make changes to the codebase, add new features or fix bugs in the project, and commit these changes locally.
Push your commits to your forked repository on GitHub using git push origin master. This will update the remote branch of your forked repository.
Go back to the original project’s page on GitHub and click on the “New pull request” button. Select your forked repository as the source branch, and the original project as the target branch.
Write a clear and concise description of the changes you made in the pull request, explaining what problem your changes solve and how they improve the project.
Submit the pull request and wait for the maintainers or owners of the project to review and potentially merge your changes into the main repository.
By following these steps, you can contribute to a GitHub project even if you’re not an official contributor or owner of the repository. Good luck with your contribution!

**Comment by RussGarratt** [comment]
Thanks @max6001  - will do
Thanks for the notice

**Comment by RussGarratt** [comment]
@sairumea 
Happy for this to be closed - thanks @max6001
