### ISSUE TITLE
[Question]: Creating Jacoco Reports

### ISSUE THREAD

**Issue by satheshsoundar** [paypal/mirakl-hyperwallet-connector#47]
Hi Team,
**Issue: Jacoco Reports not generated**
I'm trying to create Jacoco reports for Sonar Analysis. But when I execute `./gradlew clean  buildDockerCompose` jacocoTestReport.xml is not getting created.
<img width="515" alt="Screenshot 2022-06-14 at 14 01 03" src="https://user-images.githubusercontent.com/19928086/173572269-ab6a14a6-4e67-4c23-b1bd-3f3c8cd4b5e6.png">

If I try   `./gradlew clean  test buildDockerCompose` or `./gradlew clean  buildDockerCompose jacocoTestReport` _junit reports_ and  _jacocoTestReport.xml_ files are getting generated but some of the test cases are failing in kyc module.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/19928086/173574327-e7d93c53-f6e8-4d14-98be-1c40f69a2c03.png">
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/19928086/173574495-1095aa0e-5e34-4d08-8c5c-2ca59e0fdc12.png">
All the above failed tests are passing if we run separately.  

Please check this issue and let me know how to generate Jacoco Reports.

**Comment by javierpoloe2y** [comment]
Hi @satheshsoundar,

After making some tests we have found that after upgrading the version of Gradle to 7.x (and Java 17) these tests stopped failing.

We are not going to upgrade to Gradle 7.x /Java 17 yet (although we will do it probably in the future), so meanwhile we are going to disable these failing tests for the next release (4.15.0) since they are related to some simple enums and they are not so important.
